repos:
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
    - id: black
      language_version: python3.8.6
      additional_dependencies: ['click==8.0.4']
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.0
  hooks:
    - id: flake8
      args: [--max-line-length=131]