version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}

  web:
    build: .
    command: "python manage.py runserver ${HOST}:${PORT}"
    volumes:
      - .:/usr/src/app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://${USER}:${PASSWORD}@db:5432/${DBNAME}"

volumes:
  postgres_data:
